FROM continuumio/miniconda3

WORKDIR /app

# Copie les fichiers nécessaires pour créer l'environnement
COPY environment.yml .
COPY requirements.txt .

# Crée l'environnement Conda
RUN conda env create -f environment.yml && conda clean -afy

# Définit le shell par défaut pour utiliser l'environnement
SHELL ["conda", "run", "-n", "ocp-env", "/bin/bash", "-c"]

# Copie le reste du code backend
COPY . .

# Script wait-for-it
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 5000

CMD ["conda", "run", "-n", "ocp-env", "bash", "-c", "/wait-for-it.sh db:5432 -- flask init-db && flask run --host=0.0.0.0 --port=5000"]
